In [1]:
import numpy as np

In [6]:
l =["mac",1,2,3,4]

In [7]:
type(l)

list

In [8]:
np.array(l)

array(['mac', '1', '2', '3', '4'], dtype='<U11')

In [9]:
type(np.array(l))

numpy.ndarray

In [20]:
a1=np.array([1,2,2,3.0])

In [16]:
a=np.array([[1,2],[5,6]])

In [17]:
a

array([[1, 2],
       [5, 6]])

In [19]:
a[1][1]

6

In [23]:
a1

array([1., 2., 2., 3.])

In [36]:
a2=np.array([1,2,3,4,5],ndmin=4)

In [40]:
a2[0][0][0][1]

2

In [41]:
a

array([[1, 2],
       [5, 6]])

In [42]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [43]:
a= [1,2,3,4]

In [44]:
np.asarray(a)

array([1, 2, 3, 4])

In [45]:
np.mat(a)

matrix([[1, 2, 3, 4]])

In [46]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [47]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4]])

In [48]:
np.asarray(np.mat(a))

array([[1, 2, 3, 4]])

In [49]:
a

[1, 2, 3, 4]

In [50]:
type(a)

list

In [52]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
np.fromfunction(lambda i, j : 1*j ,(4,4), dtype=int)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [56]:
np.mat(np.fromfunction(lambda i, j : 1*j ,(3,4,2), dtype=int))

TypeError: <lambda>() takes 2 positional arguments but 3 were given

In [63]:
np.fromfunction(lambda i, j,z : 1*j*z ,(4,3,2), dtype=int)

array([[[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]]])

In [65]:
a

[1, 2, 3, 4]

In [66]:
a=np.fromfunction(lambda i, j,z : 1*j*z ,(4,3,2), dtype=int)

In [67]:
a

array([[[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 1],
        [0, 2]]])

In [68]:
a.ndim

3

In [69]:
a.size

24

In [70]:
a.shape

(4, 3, 2)

In [71]:
a.dtype

dtype('int32')

In [72]:
pd.Dataframe(a)

NameError: name 'pd' is not defined

In [73]:
import pandas as pd

In [74]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [75]:
a=np.fromfunction(lambda i, j : 1*j,(3,2), dtype=int)

In [76]:
pd.DataFrame(a)

0  1
0  0  1
1  0  1
2  0  1

In [78]:
np.random.rand(100,3)

array([[0.50572674, 0.08932657, 0.22123025],
       [0.50550991, 0.4050976 , 0.00910815],
       [0.69401219, 0.25994009, 0.08657359],
       [0.71554816, 0.59400467, 0.62930132],
       [0.17810291, 0.6778922 , 0.76497923],
       [0.13156098, 0.74665649, 0.3406447 ],
       [0.3731701 , 0.4101471 , 0.64921233],
       [0.09608994, 0.69746821, 0.22654838],
       [0.7260261 , 0.85273396, 0.90938851],
       [0.39257042, 0.33614411, 0.22014984],
       [0.13143903, 0.60075268, 0.7070678 ],
       [0.22802342, 0.42876921, 0.2545831 ],
       [0.05720274, 0.59744428, 0.23975835],
       [0.74715037, 0.04552107, 0.81927388],
       [0.35137923, 0.51273517, 0.44104797],
       [0.47548592, 0.80007463, 0.79167293],
       [0.38841325, 0.04853836, 0.64715061],
       [0.09839845, 0.37895435, 0.61718962],
       [0.06522879, 0.96935452, 0.93285597],
       [0.22538781, 0.68107645, 0.09664858],
       [0.99411334, 0.20203903, 0.70353512],
       [0.3571471 , 0.89067917, 0.32017044],
       [0.

In [80]:
np.random.randint(10,30)

24

In [81]:
np.random.randn(4,5)

array([[ 0.21522407, -2.10710427,  1.97817722, -0.79592244, -0.90803598],
       [ 1.82944275,  1.26708736, -0.18713828, -0.65213904, -1.09902554],
       [-1.30789985, -1.32373481, -3.30142863,  1.36636389,  0.21759296],
       [ 0.13448632, -0.87176073,  1.49275657, -0.91418601,  0.33995583]])

In [82]:
b=np.fromfunction(lambda i, j,z : 1*j*z ,(4,3,2), dtype=int)

In [84]:
b.reshape(6,4)

array([[0, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 0, 2]])

In [85]:
pd.DataFrame(b.reshape(6,4))

0  1  2  3
0  0  0  0  1
1  0  2  0  0
2  0  1  0  2
3  0  0  0  1
4  0  2  0  0
5  0  1  0  2

In [87]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [89]:
np.arange(4,10.5,2)

array([ 4.,  6.,  8., 10.])

In [90]:
arr = np.random.rand(4,5)

In [91]:
arr> .5

array([[False,  True,  True, False, False],
       [False,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False]])

In [92]:
arr[arr> .5]

array([0.62461619, 0.6414873 , 0.50360294, 0.86700478, 0.72166708,
       0.75351945, 0.64821647, 0.9827781 , 0.99423785, 0.65407324])

In [93]:
arr

array([[0.09860622, 0.62461619, 0.6414873 , 0.19863922, 0.37926517],
       [0.12932955, 0.50360294, 0.32433502, 0.86700478, 0.72166708],
       [0.75351945, 0.37612812, 0.64821647, 0.9827781 , 0.99423785],
       [0.65407324, 0.21782666, 0.40871355, 0.29880625, 0.48637056]])

In [96]:
arr[[2,3],[3]]

array([0.9827781 , 0.29880625])

In [97]:
a2=np.random.rand(8,5)

In [98]:
a2

array([[0.77272786, 0.00603443, 0.57720375, 0.60461538, 0.30573635],
       [0.82623371, 0.35586384, 0.52369906, 0.61464721, 0.19238005],
       [0.77387484, 0.56773864, 0.5287407 , 0.92037447, 0.22467758],
       [0.62316664, 0.48404812, 0.01066544, 0.82824677, 0.01744887],
       [0.59235736, 0.10477481, 0.03203881, 0.13022149, 0.57153069],
       [0.75807986, 0.08555534, 0.82591448, 0.31589667, 0.61156557],
       [0.31713749, 0.2683879 , 0.74577052, 0.16517142, 0.00485879],
       [0.47939576, 0.43902282, 0.86431761, 0.22553432, 0.3994827 ]])

In [101]:
a2[1:8, 0:3]

array([[0.82623371, 0.35586384, 0.52369906],
       [0.77387484, 0.56773864, 0.5287407 ],
       [0.62316664, 0.48404812, 0.01066544],
       [0.59235736, 0.10477481, 0.03203881],
       [0.75807986, 0.08555534, 0.82591448],
       [0.31713749, 0.2683879 , 0.74577052],
       [0.47939576, 0.43902282, 0.86431761]])

In [106]:
a2[0][0]= 1

In [107]:
a2

array([[1.        , 0.00603443, 0.57720375, 0.60461538, 0.30573635],
       [0.82623371, 0.35586384, 0.52369906, 0.61464721, 0.19238005],
       [0.77387484, 0.56773864, 0.5287407 , 0.92037447, 0.22467758],
       [0.62316664, 0.48404812, 0.01066544, 0.82824677, 0.01744887],
       [0.59235736, 0.10477481, 0.03203881, 0.13022149, 0.57153069],
       [0.75807986, 0.08555534, 0.82591448, 0.31589667, 0.61156557],
       [0.31713749, 0.2683879 , 0.74577052, 0.16517142, 0.00485879],
       [0.47939576, 0.43902282, 0.86431761, 0.22553432, 0.3994827 ]])

In [108]:
a= np.array([[1,2],[3,4]])
b= np.array([[3,5],[7,8]])

In [109]:
a*b

array([[ 3, 10],
       [21, 32]])

In [110]:
a

array([[1, 2],
       [3, 4]])

In [111]:
b

array([[3, 5],
       [7, 8]])

In [112]:
a*b

array([[ 3, 10],
       [21, 32]])

In [114]:
m=a@b

In [115]:
m/0

C:\Users\INTEGRAL COMPUTER\AppData\Local\Temp\ipykernel_3904\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
a= [1,2,3,4,]

In [4]:
np.array(a)

array([1, 2, 3, 4])

In [5]:
pd.DataFrame(np.array(a))

0
0  1
1  2
2  3
3  4

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.45041255e-307, 1.89145198e-307],
       [3.44897822e-307, 4.45043631e-307, 8.34441742e-308,
        1.78022342e-306, 6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307, 1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306, 2.22507386e-306]])

In [16]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [17]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [20]:
np.linspace(2,6,10,endpoint=False)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [25]:
np.linspace(2,6,10,retstep=True)

(array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
        4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]),
 0.4444444444444444)

In [27]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [28]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
a=np.arange(16).reshape(4,4)

In [33]:
a.max()

15

In [34]:
a.max(aixs= 1)

TypeError: _amax() got an unexpected keyword argument 'aixs'

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
a=np.arange(4,40).reshape(3,6,2)

In [38]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [39]:
a.max()

39

In [40]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [41]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [46]:
a1=a.reshape(6,6)

In [48]:
10+a1

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [50]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [51]:
a**2

array([[[  16,   25],
        [  36,   49],
        [  64,   81],
        [ 100,  121],
        [ 144,  169],
        [ 196,  225]],

       [[ 256,  289],
        [ 324,  361],
        [ 400,  441],
        [ 484,  529],
        [ 576,  625],
        [ 676,  729]],

       [[ 784,  841],
        [ 900,  961],
        [1024, 1089],
        [1156, 1225],
        [1296, 1369],
        [1444, 1521]]])

In [52]:
a1**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [54]:
pow(a1,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [55]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [60]:
b=np.array([2,3,1,2,3,2])

In [61]:
b

array([2, 3, 1, 2, 3, 2])

In [62]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [64]:
a1+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [66]:
a1+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [67]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [68]:
a1**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [69]:
np.sqrt(a1)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [70]:
np.square(a1)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [72]:
np.exp(a1)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [74]:
np.log10(a1)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [76]:
x= np.array([1,2,3])

In [77]:
y=x

In [78]:
y

array([1, 2, 3])

In [79]:
x


array([1, 2, 3])

In [80]:
z= np.copy(x)

In [81]:
z

array([1, 2, 3])

In [83]:
x[0]= 100

In [84]:
x

array([100,   2,   3])

In [85]:
y

array([100,   2,   3])

In [86]:
z

array([1, 2, 3])

In [87]:
id(x)

2130782953584

In [88]:
id(y)

2130782953584

In [89]:
id(z)

2130740579376

In [91]:
id(x[0])

2130783012752

In [92]:
id(y[0])

2130783023152